export const ACTION_CONFLUENCE_LOGIN = 'ACTION_CONFLUENCE_LOGIN';
export const ACTION_CONFLUENCE_CONTENT = 'ACTION_CONFLUENCE_CONTENT';
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';